spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    dbcp2:
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
    hikari:
      max-lifetime: 500000
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /static/**
  cache:
    ehcache:
      config: classpath:ehcache.xml
  mail:
    host: smtp.163.com
    username: 1927457049@qq.com
    password: # 授权第三方登录的授权码
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 994 #465或者994
    properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8
      from: emple_3usoft@163.com

logging:
  level:
    root: jar
    com.blog: info
  file:
    name: log/myblog-pro.log

mybatis:
  type-aliases-package: com.myblog.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
myblog:
  lucene-index-path: #生产环境存放Lucene索引的路径