# 是否开启kafka和swagger
zhangjianbing:
  web:
    logging:
      kafka:
        enabled: false # 是否推送日志到kafka
        broker: 192.168.23.133:6379,192.168.23.133:6379,192.168.23.133:6379
        env: prod
    swagger:
      enabled: false # 是否开启swagger，生产环境关闭
      description: myblog
      basePackage: com.myblog.controller
      version: v1.0.3
      contact:
        name: myblog
        url: https://www.zhangjianbing.com
        email: 1927457049@qq.com

# 日志存储位置，以及debug级别日志输出路径
logging:
  level:
    ROOT: info
    com:
      myblog:
          mapper: debug
  file:
    path: /data/myblog/logs


# 数据库加密秘钥
jasypt:
  encryptor:
    password: root

# 指定mapper位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.myblog.mapper

# 指定服务端口号，以及文件上传临时存储问题
server:
  port: 8080
  tomcat:
    basedir: /data/apps/temp
spring:
  devtools:
    restart:                # 按特定时间间隔轮询类更改，然后等待预定义的静默期以确保没有更多更改
      poll-interval: 2s
      quiet-period: 1s
      enabled: true         # 设置开启热部署
      additional-paths:
        - src/main/java     # 重启目录
    remote:
      secret: mysecret      # 安全配置
      proxy:
        https: //
        host: 192.168.80.1
        port: 8080
  main:                     # 延迟初始化
    lazy-initializatio: true
  application:
    name:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    oracleucp:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      max-pool-size: 20
    dbcp2:
      initial-size: 5
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      min-idle: 5
      min-evictable-idle-time-millis: 300000
    tomcat:
      max-active: 20
      max-wait: 60000
  mail:
    username: 1927457049@qq.com
    password: 20000506lyh@
    host: smtp.qq.com
    port: 25
  redis:
    host: 192.168.23.133
    password: 123456
    port: 6379
    timeout: 50000
  thymeleaf:
    cache: false
    mode: HTML
